# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-02-13 00:48:47
"""
import arcpy

def MovePointsToLine():  # Move Ponits to Line

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    realop_csv = "Z:\\Comm_Rail\\doc\\realop.csv"
    H_Line = "Z:\\Comm_Rail\\Comm_Rail.gdb\\H_Line"

    # Process: XY Table To Point (2) (XY Table To Point) (management)
    realop = "Z:\\Comm_Rail\\Comm_Rail.gdb\\realop"
    arcpy.management.XYTableToPoint(in_table=realop_csv, out_feature_class=realop, x_field="longitude", y_field="latitude", coordinate_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision")

    # Process: Buffer the Routes (Pairwise Buffer) (analysis)
    H_Line_buffer = "Z:\\Comm_Rail\\Comm_Rail.gdb\\H_Line_buffer"
    arcpy.analysis.PairwiseBuffer(in_features=H_Line, out_feature_class=H_Line_buffer, buffer_distance_or_field="15 Meters", dissolve_option="NONE", method="PLANAR", max_deviation="0 Meters")

    # Process: Clip realop along the railway (Pairwise Clip) (analysis)
    H_Line_Realop = "Z:\\Comm_Rail\\Comm_Rail.gdb\\H_Line_Realop"
    arcpy.analysis.PairwiseClip(in_features=realop, clip_features=H_Line_buffer, out_feature_class=H_Line_Realop)

    # Process: Near (Near) (analysis)
    H_Line_Realop_2_ = arcpy.analysis.Near(in_features=H_Line_Realop, near_features=[H_Line], search_radius="15 Meters", location="LOCATION", angle="NO_ANGLE", method="PLANAR", field_names=[["NEAR_FID", "NEAR_FID"], ["NEAR_DIST", "NEAR_DIST"], ["NEAR_X", "NEAR_X"], ["NEAR_Y", "NEAR_Y"]])[0]

    # Process: XY Table To Point (XY Table To Point) (management)
    Realop_n = "Z:\\Comm_Rail\\Comm_Rail.gdb\\realop_n"
    arcpy.management.XYTableToPoint(in_table=H_Line_Realop_2_, out_feature_class=Realop_n, x_field="NEAR_X", y_field="NEAR_Y", coordinate_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="Z:\\Comm_Rail\\Comm_Rail.gdb", workspace="Z:\\Comm_Rail\\Comm_Rail.gdb"):
        MovePointsToLine()
