---
title: "SpeedML"
author: "Jia-Shen Tsai,  Wendy Wen, Zhengqi Jiao, Miaojun Pang, Alexander Yoshizumi"
date: "2024-03-02"
last updated: "2024-03-12"
output: html_document
---
When run, the script create the random forest model and results for the given dataset.

```{r setup, message = FALSE, warning = FALSE}
rm(list=ls())

library(ggplot2)
library(dplyr)
library(randomForest)
# devtools::install_github("MI2DataLab/randomForestExplainer")
library(randomForestExplainer)
library(leaflet)
```

```{r reading files, message = FALSE, warning = FALSE}
df_all <- read.csv("../01_Data/02_Processed/randomForest/Speed_Model_R_v4.csv")
df_east <- read.csv("../01_Data/02_Processed/randomForest/Speed_Model_East_v4.csv")
df_west <- read.csv("../01_Data/02_Processed/randomForest/Speed_Model_West_v4.csv")

str(df_all)
dim(df_east)
dim(df_west)
```
```{r optimal mtry}
mean(df_all$Speed_mph)
optimal_mtry <- tuneRF(df_all[,-1], df_all[,1])
```

```{r create a forest, message = FALSE, warning = FALSE}
set.seed(2026)
forest <- randomForest(Speed_mph ~ ., data = df_all, localImp = TRUE)
forest
```

# Distribution of minimal depth
```{r Create Minimal depth for each variable, warning = FALSE}
#min_depth_frame <- min_depth_distribution(forest)
#save(min_depth_frame, file = '../01_Data/02_Processed/randomForest/min_depth_fram.rda')
load('../01_Data/02_Processed/randomForest/min_depth_fram.rda')
head(min_depth_frame, n=10)
```
```{r Minimal Depth Distribution Plot , warning = FALSE, fig.width=10}
plot_min_depth_distribution(min_depth_frame)
```
```{r Minimal Depth Distribution Plot without missing values, warning = FALSE, fig.width=10}
plot_min_depth_distribution(min_depth_frame, mean_sample = "relevant_trees", k = 15)
```

# Various variable importance measures
```{r Importance Frame, warning = FALSE}
#importance_frame <- measure_importance(forest)
#save(importance_frame, file = "../01_Data/02_Processed/randomForest/importance_frame.rda")
load("../01_Data/02_Processed/randomForest/importance_frame.rda")
importance_frame
```
```{r Multi-Way Importance Plot, warning = FALSE}
# plot_multi_way_importance(forest, size_measure = "no_of_nodes") # gives the same result as below but takes longer
plot_multi_way_importance(importance_frame, size_measure = "no_of_nodes")
```
```{r Multi-way importance plot with p-value, warning = FALSE}
plot_multi_way_importance(importance_frame, x_measure = "mse_increase", y_measure = "node_purity_increase", size_measure = "p_value", no_of_labels = 5)
```

## Compare measures using ggpairs
```{r Relations between measures of importance, message = FALSE, warning = FALSE}
# plot_importance_ggpairs(forest) # gives the same result as below but takes longer
plot_importance_ggpairs(importance_frame)
```

## Compare different rankings
```{r Relations between rankings according to different measures, message = FALSE, warning = FALSE}
# plot_importance_rankings(forest) # gives the same result as below but takes longer
plot_importance_rankings(importance_frame)
```

# Variable Interactions
## Conditional minimal depth
```{r Extract the names of 5 most important variables according to both the mean minimal depth and number of trees, warning = FALSE}
# (vars <- important_variables(forest, k = 5, measures = c("mean_min_depth", "no_of_trees"))) # gives the same result as below but takes longer
(vars <- important_variables(importance_frame, k = 5, measures = c("mean_min_depth", "no_of_trees")))

```
```{r Interaction frame with interactions, warning = FALSE}
#interactions_frame <- min_depth_interactions(forest, vars)
#save(interactions_frame, file = "../01_Data/02_Processed/randomForest/interactions_frame.rda")
load("../01_Data/02_Processed/randomForest/interactions_frame.rda")
head(interactions_frame[order(interactions_frame$occurrences, decreasing = TRUE), ])
```

```{r Mean minimal depth for 30 most frequent interactions, warning = FALSE, fig.width=10}
# plot_min_depth_interactions(forest) # calculates the interactions_frame for default settings so may give different results than the function below depending on our settings and takes more time
plot_min_depth_interactions(interactions_frame)
```

```{r Mean minimal depth for 30 most frequent interactions without missing values, warning = FALSE, fig.width=10}
#interactions_frame <- min_depth_interactions(forest, vars, mean_sample = "relevant_trees", uncond_mean_sample = "relevant_trees")
#save(interactions_frame, file = "../01_Data/02_Processed/randomForest/interactions_frame_relevant.rda")
load("../01_Data/02_Processed/randomForest/interactions_frame_relevant.rda")
plot_min_depth_interactions(interactions_frame)
```

## Predict of the forest on a grid
```{r Prediction of the forest by interactions, warning = FALSE}
plot_predict_interaction(forest, df_all, "Distance_to_FOL_Station", "Elev_Delta_FOL_1k5_2kft_ft")
```

```{r}
explain_forest(forest, interactions = TRUE, data = df_all)
```
# Predict
```{r input dataset}
df_exact <- read.csv("../01_Data/02_Processed/randomForest/TestData_exact.csv")
df_station <- read.csv("../01_Data/02_Processed/GIS/Stations_LT.csv")
```


```{r}
# Step 2: Predict outcomes for the test set
predictions_exact <- predict(forest, newdata = df_exact)
```

```{r add the column back to test data}
df_exact$Speed_mph <- predictions_exact

```

```{r}
# Prepare the text for the tooltip:
mytext <- paste(
  df_station$Station_Name) %>%
  lapply(htmltools::HTML)

s <- leaflet(df_station) %>% 
  addTiles()  %>% 
  addProviderTiles("Esri.WorldImagery") %>%
  addCircleMarkers(~x_coordinate, ~y_coordinate, 
    fillOpacity = 0.7, color="lawngreen", radius=6, stroke=FALSE,
    label = mytext,
    labelOptions = labelOptions( style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "13px", direction = "auto")
  )
s
```


```{r plot the speed on a map}

mytext <- paste(
  df_station$Station_Name) %>%
  lapply(htmltools::HTML)

mybins <- seq(0, 80, by=5)
mypalette <- colorBin(palette="viridis", domain=df_exact$Speed_mph, na.color="transparent", bins=mybins)

m <- leaflet(df_exact, height = 640, width = 640) %>%
  addTiles() %>%
  addCircleMarkers(lng = ~x_coordinate, lat = ~y_coordinate,
                   fillColor = ~mypalette(Speed_mph), fillOpacity = 1, radius=5, stroke=FALSE) %>%
  addCircles(lng = df_station$x_coordinate,
             lat = df_station$y_coordinate,
             radius = 2,
             color = "red",
             fill = T,
             fillColor = "red",
             fillOpacity = 1,
             popup = df_station$Station_Name,
             label = mytext, 
             labelOptions = labelOptions(
             textsize = "13px",
             direction = "left",
             offset = c(0, 10))
             ) %>%
  setView(lng = -78.72, lat = 35.84, zoom = 10) %>%
  addLegend(pal=mypalette, values=~Speed_mph, opacity=0.9, title = "Average Speed (mph)", position = "topright" ) %>%
  addProviderTiles("Stadia.AlidadeSmooth")

m

```


```{r}
write.csv(df_exact, "../01_Data/02_Processed/randomForest/Prediction_exact.csv", row.names = FALSE)
```

